spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/pingpong
    username: sa
    password:
    driver-class-name: org.h2.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  output:
    ansi:
      enabled: always

jwt:
  secret:
    key: akjbfiu23bfafnaji3889adskjndskjdsfnalaiweufh